### ISSUE TITLE
Cannot remove custom SP

### ISSUE THREAD

**Issue by AdamNowaczyk** [samlidp/samlidp.io#1]
I added custom SP through metadata XML. However I cannot remove it now.

![image](https://cloud.githubusercontent.com/assets/5577457/26193568/fef39098-3bb5-11e7-952e-a2cec61d8b79.png)

It's development server, so probably I did something wrong, but is there a way of force removing the SP?

**Comment by sitya** [comment]
Which one is your IdP? And what is the entityID of your test SP? I'll check the logs.

**Comment by sitya** [comment]
OK, I see the bug. I will fix it soon.

**Comment by AdamNowaczyk** [comment]
It's https://acaisoft.samlidp.io and SP name is acaisoft.samlidp.io

**Comment by sitya** [comment]
It has been fixed, the deployment is on its way, it is 15-20 minutes.

**Comment by sitya** [comment]
It is working now, I have checked it. Thanks for the reporting (the problem came when there were multiple custom SP registered and not the first one was to be deleted). Any feedback is more than welcome :)

**Comment by AdamNowaczyk** [comment]
Thanks, it works. Very impressed with quick response/fix time 👍

**Comment by sitya** [comment]
Thanks. :)

One more remark - I have just seen in the logs. The SP you are using for testing does not have a certificate in its metadata. It must be present, because the IdP uses the public key of the SP for sending back the encrypted assertion. It cannot be sent unencrypted [1]. 

Anyway, we will put a checkpoint into the SP import function to ensure if SP does have x509 certificate in the metadata.

[1]: https://samlidp.io/privacypolicy (point nr. 2.)
